In [1]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

print(certificates_earned.iloc[2])

Certificates        5
Time (in months)    9
Name: Ahmad, dtype: int64


In [1]:
import numpy as np
a=np.array([1,2,3,5,6])
a

array([1, 2, 3, 5, 6])

In [9]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [10]:
a+10

array([10, 11, 12, 13, 14])

In [11]:
a*10

array([ 0, 10, 20, 30, 40])

In [12]:
a+=100

In [13]:
a

array([100, 101, 102, 103, 104])

In [14]:
l=[1,2,3,4]
[i*10 for i in l]

[10, 20, 30, 40]

In [15]:
b=([3,4,5,6])
b

[3, 4, 5, 6]

In [23]:
b=np.arange(5)

In [24]:
b

array([0, 1, 2, 3, 4])

In [26]:
b=np.array([10,20,30,40,50])
b

array([10, 20, 30, 40, 50])

In [27]:
a*b

array([1000, 2020, 3060, 4120, 5200])

In [28]:
a+b

array([110, 121, 132, 143, 154])

In [29]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [30]:
a[0],a[-1]

(0, 3)

In [31]:
a[[False,True,True,False]]

array([1, 2])

In [32]:
a

array([0, 1, 2, 3])

In [33]:
a>=2

array([False, False,  True,  True])

In [34]:
a<=2

array([ True,  True,  True, False])

In [35]:
a.mean()

1.5

In [36]:
a[a>a.mean()]

array([2, 3])

In [37]:
a[~(a>a.mean())]

array([0, 1])

In [38]:
B=np.random.randint(100,size=(4,4))

In [39]:
B

array([[54, 73, 56, 78],
       [23, 40,  1, 37],
       [81, 24, 31,  1],
       [64, 60, 93, 69]])

In [40]:
B>40

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False, False],
       [ True,  True,  True,  True]])

In [41]:
B[B>50]

array([54, 73, 56, 78, 81, 64, 60, 93, 69])

In [45]:
#linear algebra
A=np.array([
    [1,2,3],
    [4,5,6],
    [5,6,7]
])

In [46]:
B=np.array([
    [5,6,7],
    [7,8,9],
    [8,9,1]
])

In [47]:
A.dot(B)

array([[ 43,  49,  28],
       [103, 118,  79],
       [123, 141,  96]])

In [48]:
A@B

array([[ 43,  49,  28],
       [103, 118,  79],
       [123, 141,  96]])

In [49]:
B.T

array([[5, 7, 8],
       [6, 8, 9],
       [7, 9, 1]])

In [50]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [51]:
B.T@A

array([[ 73,  93, 113],
       [ 83, 106, 129],
       [ 48,  65,  82]])

In [54]:
#size of objects in memory 
#An integar in python is >24bytes


In [ ]:
l=list(range(100000))

In [57]:
a=np.arange(100000)
%time np.sum(a**2)

Wall time: 0 ns


216474736

In [58]:
#useful numpy functions 
np.random.random(size=2)

array([0.12058837, 0.76404347])

In [59]:
np.random.normal(size=2)

array([0.0172244 , 0.28025467])

In [60]:
np.random.rand(2,4)

array([[0.70461708, 0.46915522, 0.784452  , 0.52190355],
       [0.50110223, 0.37675427, 0.74126986, 0.54753871]])

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [63]:
np.arange(0,1,-1)

array([], dtype=int32)

In [64]:
#reshape
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [67]:
#linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [68]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [74]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
"Hello World"[7]

'o'

In [83]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
np.arange(10 ,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [87]:
np.ones((2,2), dtype=np.int)

C:\Users\Ayush-PC\AppData\Local\Temp/ipykernel_1660/3210661313.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((2,2), dtype=np.int)


array([[1, 1],
       [1, 1]])

In [88]:
np.ones((3,2),dtype=np.float)

C:\Users\Ayush-PC\AppData\Local\Temp/ipykernel_1660/3838854983.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((3,2),dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Handling Missing values with pandas 


In [10]:
#about g7 in millions
import numpy as np 
import pandas as pd


In [12]:
g7_pop=pd.Series([35.467,63.951,80.940,60.665,127.061,64.511,312.450])

In [13]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    312.450
dtype: float64

In [14]:
g7_pop.name = "G7 populations in millions"

In [15]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    312.450
Name: G7 populations in millions, dtype: float64

In [16]:
g7_pop.dtype

dtype('float64')

In [17]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 312.45 ])

In [18]:
type(g7_pop.values)

numpy.ndarray

In [19]:
g7_pop[0]

35.467

In [20]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [21]:
g7_pop.index=[
    'Canada','France','Germany','Italy','Japan','Uk','UN'
]

In [22]:
g7_pop

Canada      35.467
France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
Uk          64.511
UN         312.450
Name: G7 populations in millions, dtype: float64

# Indexing

In [23]:
g7_pop['Canada']

35.467

In [24]:
#Numeric positions can also be used, with the iloc attribute
g7_pop.iloc[0]

35.467

In [25]:
#Selecting multiple elements at once:
g7_pop[['Italy','France']]

Italy     60.665
France    63.951
Name: G7 populations in millions, dtype: float64

In [27]:
#Slicing also works, but important, in Pandas, the upper limit is also included:
g7_pop.iloc[[2,3]]

Germany    80.940
Italy      60.665
Name: G7 populations in millions, dtype: float64

# Conditional selection (boolean arrays)

In [28]:
g7_pop

Canada      35.467
France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
Uk          64.511
UN         312.450
Name: G7 populations in millions, dtype: float64

In [29]:
g7_pop>80

Canada     False
France     False
Germany     True
Italy      False
Japan       True
Uk         False
UN          True
Name: G7 populations in millions, dtype: bool

In [30]:
g7_pop[g7_pop>80]

Germany     80.940
Japan      127.061
UN         312.450
Name: G7 populations in millions, dtype: float64

In [31]:
g7_pop.mean()

106.43500000000002

In [32]:
g7_pop[g7_pop>g7_pop.mean()]

Japan    127.061
UN       312.450
Name: G7 populations in millions, dtype: float64

In [34]:
g7_pop.std()

95.05390495397862

In [35]:
g7_pop[(g7_pop>g7_pop.mean()-g7_pop.std()/2)|(g7_pop > g7_pop.mean() + g7_pop.std() / 2)]

France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
Uk          64.511
UN         312.450
Name: G7 populations in millions, dtype: float64

# Operations & Methods 

In [36]:
g7_pop*1000000

Canada      35467000.0
France      63951000.0
Germany     80940000.0
Italy       60665000.0
Japan      127061000.0
Uk          64511000.0
UN         312450000.0
Name: G7 populations in millions, dtype: float64

In [37]:
g7_pop.mean()

106.43500000000002

In [38]:
np.log(g7_pop)

Canada     3.568603
France     4.158117
Germany    4.393708
Italy      4.105367
Japan      4.844667
Uk         4.166836
UN         5.744444
Name: G7 populations in millions, dtype: float64

In [39]:
g7_pop['France':'Italy'].mean()

68.51866666666666

# Modifying Series

In [41]:
g7_pop['Canada']=40.5

In [42]:
g7_pop

Canada      40.500
France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
Uk          64.511
UN         312.450
Name: G7 populations in millions, dtype: float64

In [43]:
g7_pop.iloc[-1]=500

In [44]:
g7_pop

Canada      40.500
France      63.951
Germany     80.940
Italy       60.665
Japan      127.061
Uk          64.511
UN         500.000
Name: G7 populations in millions, dtype: float64

In [45]:
g7_pop[g7_pop < 70] = 99.99

In [46]:
g7_pop

Canada      99.990
France      99.990
Germany     80.940
Italy       99.990
Japan      127.061
Uk          99.990
UN         500.000
Name: G7 populations in millions, dtype: float64

In [1]:
import numpy as np 

In [2]:
a=np.array([1,2,3])
b=np.array([3,4,5])
a*b

array([ 3,  8, 15])

In [3]:
a=[1,2,3]
b=[2,3,4]
a*b

TypeError: can't multiply sequence by non-int of type 'list'