In [1]:
import numpy as np 
import pandas as pd

In [2]:
#For Python, all the values above are considered "falsy":
falsy_values=(0,False,None,'',[],{})

In [3]:
any(falsy_values)

False

In [4]:
#Numpy has a special "nullable" value for numbers which is np.nan. It's NaN: "Not a number"
np.nan

nan

In [5]:
#Numpy has a special "nullable" value for numbers which is np.nan. It's NaN: "Not a number"
3+np.nan

nan

In [6]:
a=np.array([1,2,3,np.nan,np.nan,4])

In [7]:
a.sum()

nan

In [8]:
a.mean()

nan

In [11]:
3 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [12]:
a=np.array([1,2,3,np.nan,None,4],dtype='float')

In [13]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [14]:
#Numpy also supports an "Infinite" type:
np.inf

inf

In [15]:
3+np.inf

inf

In [16]:
np.inf/3

inf

In [17]:
np.inf/np.inf

nan

In [18]:
b=np.array([1,2,3,np.inf,np.nan,4],dtype=np.float)

C:\Users\Ayush-PC\AppData\Local\Temp/ipykernel_11908/2727255339.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.array([1,2,3,np.inf,np.nan,4],dtype=np.float)


In [19]:
b.sum()

nan

# Checking for nan or inf
There are two functions: np.isnan and np.isinf that will perform the desired checks:

In [20]:
np.isnan(np.nan)

True

In [21]:
np.isinf(np.inf)

True

In [22]:
#And the joint operation can be performed with np.isfinite.
np.isfinite(np.nan), np.isfinite(np.inf)



(False, False)

In [24]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False,  True, False, False])

In [25]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False, False,  True, False])

In [26]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([ True,  True,  True, False, False,  True])

In [27]:
#Note: It's not so common to find infinite values. From now on, we'll keep working with only np.nan



In [28]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])


In [29]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [31]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [32]:
a[np.isfinite(a)].sum()

10.0

In [33]:
a[np.isfinite(a)].mean()

2.5