In [8]:
import numpy as np 


In [9]:
a=np.array([1,2,3])
b=np.array([3,4,5])
a*b

array([ 3,  8, 15])

In [10]:
a=[3,4,5]
b=[3,6,7]
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
a=np.array([2,3,4],dtype='int')
a

array([2, 3, 4])

In [12]:
b=np.array([[3,4,5],[6,7,8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [13]:
a.shape


(3,)

In [14]:
b.shape

(2, 3)

In [15]:
#get dimension
a.ndim

1

In [16]:
b.ndim

2

In [17]:
a.dtype

dtype('int32')

In [18]:
x=np.array([[1,2,3,5,6,7],[4,7,8,9,23,78]])
x

array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  7,  8,  9, 23, 78]])

In [19]:
x.shape

(2, 6)

In [20]:
#get a specific elements 
x[1,-3]

9

In [21]:
#get a specific row 
x[-1:]

array([[ 4,  7,  8,  9, 23, 78]])

In [22]:
#get a specific column
x[:,-1]

array([ 7, 78])

In [23]:
#Getting more fancy [startindex:endindex:stepsize]
x[0,1:-2:2]

array([2, 5])

In [24]:
#change the value of any elements 
x[0,1]=45
x

array([[ 1, 45,  3,  5,  6,  7],
       [ 4,  7,  8,  9, 23, 78]])

In [25]:
#3d array 
b=np.array([[[2,3],[3,4]],[[6,7],[8,9]]])
b

array([[[2, 3],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [26]:
#Get the specific elements (work outside in)
b[1,0,0]

6

In [27]:
#replace value 
b[1,0,0]=88
b

array([[[ 2,  3],
        [ 3,  4]],

       [[88,  7],
        [ 8,  9]]])

In [28]:
b[:,0,:]=[[9,9],[9,9]]
b

array([[[9, 9],
        [3, 4]],

       [[9, 9],
        [8, 9]]])

# Initializing different types of array

In [29]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
np.ones((3,2,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [34]:
#any other numbers
np.full((3,4),77)

array([[77, 77, 77, 77],
       [77, 77, 77, 77],
       [77, 77, 77, 77]])

In [35]:
#we can write in both ways in full
np.full_like(b,44)

array([[[44, 44],
        [44, 44]],

       [[44, 44],
        [44, 44]]])

In [36]:
np.full(b.shape ,55)

array([[[55, 55],
        [55, 55]],

       [[55, 55],
        [55, 55]]])

In [37]:
#random decimal values 
np.random.rand(4,5)

array([[0.88318662, 0.84839847, 0.64827705, 0.08792623, 0.30838856],
       [0.27390913, 0.17069069, 0.28601759, 0.40079659, 0.6071545 ],
       [0.11618324, 0.36679367, 0.28560899, 0.21108413, 0.12040729],
       [0.6335415 , 0.87902304, 0.10877283, 0.52738997, 0.73646982]])

In [38]:
#random integar values 
np.random.randint(6,size=(4,5))

array([[1, 3, 1, 4, 2],
       [2, 2, 1, 0, 2],
       [3, 2, 0, 0, 3],
       [3, 2, 5, 1, 5]])

In [39]:
np.random.rand(b.size)

array([0.89610779, 0.87913246, 0.15835906, 0.37869731, 0.94906021,
       0.60922267, 0.00940914, 0.70541464])

In [40]:
#identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


# Initialize array problems

In [42]:
x=np.ones((5,5))
print(x)
y=np.zeros((3,3))
y[1,1]=9
print(y)
x[1:-1,1:-1]=y
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# copying array warning 

Be careful when copy array because when we initialize a=b then it become equal but when we change the value of 'a' then it doesnt what actually 'b'is , so for that we use .copy() function

In [43]:
a=np.array([4,5,6])
b=a.copy()
b[0]=100
print(a)


[4 5 6]


# Mathematics

In [44]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [45]:
a+2

array([3, 4, 5, 6])

In [46]:
a-2

array([-1,  0,  1,  2])

In [47]:
a*2

array([2, 4, 6, 8])

In [48]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [49]:
b=np.array([3,4,5,6])
a+b

array([ 4,  6,  8, 10])

In [50]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [51]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [52]:
np.cos(b)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [53]:
#docs.scipy.org


# Linear Algebra

In [54]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [55]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [56]:
#things to learn
#Determint 
#Eigen Values & vectors
#Trace
#singular value decomposition 
#inverse
#Matrix Norm 


# Statistics

In [57]:
stats=np.array([[2,3,4],[6,7,8]])
stats

array([[2, 3, 4],
       [6, 7, 8]])

In [58]:
np.min(stats,axis=1)

array([2, 6])

In [59]:
np.max(stats,axis=1)

array([4, 8])

In [60]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
print(b)

15


# Reorganizing Array

In [61]:
before=np.array([[1,2,3,6],[4,5,6,7]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 6]
 [4 5 6 7]]
[[1 2]
 [3 6]
 [4 5]
 [6 7]]


In [62]:
#Vertically Stacking Vectors 
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v1])
#here we can do copying of same elements 

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [63]:
 #horizontal stacking   
h1=np.array([1,2,3,4])
h2=np.ones((4))
np.hstack((h1,h2))

array([1., 2., 3., 4., 1., 1., 1., 1.])

# loading data & advanced indexing

In [67]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  5.,  6., 78., 89., 90., 23., 45.,  9., 12.],
       [56., 78., 89., 90., 22., 45., 67., 17., 16., 12.]])

# boolean masking & advanced indexing 

In [68]:
filedata>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False, False,
        False],
       [ True,  True,  True,  True, False, False,  True, False, False,
        False]])

In [69]:
filedata[filedata>50]

array([78., 89., 90., 56., 78., 89., 90., 67.])

In [73]:
filedata[2]

array([56., 78., 89., 90., 22., 45., 67., 17., 16., 12.])

In [74]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False, False,
        False],
       [ True,  True,  True,  True, False, False,  True, False, False,
        False]])